### ISSUE TITLE
Review for missing content - at_contacts_flutter (Scores Tab)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_widgets#83] opened 2021-07-22 00:42 UTC
[Scores tab](https://pub.dev/packages/at_contacts_flutter/score) missing documentation for:

- [x] provide documentation
- [ ] support multiple platforms
- [ ] support sound null safety

**Comment by ksanty** [comment] 2021-11-25 17:33
Hi @sachins-geekyants we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue.  Creating new issue cards today.

**Comment by sachins-geekyants** [comment] 2021-11-29 11:43
Duplicate of [this](https://github.com/atsign-foundation/.github/issues/6) ticket.

**Closed by sachins-geekyants** 2021-11-29 11:43 UTC
Labels: documentation
