### ISSUE TITLE
Onboarding Widget - unable to activate staging atsigns

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_widgets#161] opened 2021-08-23 14:48 UTC
**Describe the bug**
When running atmosphere or atmosphere pro locally, I tried activating atsigns in staging and did not receive any of the emails with the verification codes. Sarika says she has faced the same issue while testing on staging.

**To Reproduce**
1. Build and run atmosphere or atmosphere pro using the trunk branch (this points to staging)
2. Attempt to activate one of your staging atsigns. The email containing the 4 character code will not arrive

**Expected behavior**
We should be able to activate atsigns in staging

**Smartphone (please complete the following information):**
 - Device: iOS iphone 11 simulator and Android emulator

**Were you using an @‎application when the bug was found?**
  - atmosphere and atmosphere pro

**Comment by murali-shris** [comment] 2021-08-24 13:36
@sarika01 please add the exact error you faced

**Comment by sarika01** [comment] 2021-08-25 11:29
I have reset and activated an atsign (@ 2418permanent) on staging.

<img width="1180" alt="Screenshot 2021-08-25 at 4 46 28 PM" src="https://user-images.githubusercontent.com/12222326/130782805-6e555cc0-70bf-42bd-b6fc-18be1b098d7a.png">


Upon trying to onboard it, I am getting this issue:


https://user-images.githubusercontent.com/12222326/130782876-6e9e9e28-2ec8-41e6-ad8e-db88a392af1e.mov


No error is seen in app logs.

**Comment by sarika01** [comment] 2021-08-25 11:34
Secondly, I tried to get a new atsign. Even though I received the OTP, the activation spinner just went on and on:

https://user-images.githubusercontent.com/12222326/130783528-db615598-2d6d-42fd-8f28-0288bb81f5e6.mov

And observed this issue in the app log:

<img width="1324" alt="Screenshot 2021-08-25 at 4 56 12 PM" src="https://user-images.githubusercontent.com/12222326/130783622-4242e75e-ee3b-4598-bafa-a768d2cd1c1b.png">

**Comment by yahu1031** [comment] 2021-08-25 14:19
Hey @sarika01, How about setting up your `rootDomain` to staging
```dart
AtStatusImpl atStatusImpl = AtStatusImpl(rootUrl: HERE);
```
By default, it will be `root.atsign.org` in [`at_server_status`](https://pub.dev/packages/at_server_status).
please provide info about this. 😺

**Comment by yahu1031** [comment] 2021-09-09 07:57
@sarika01 For some reason, we cannot reproduce it. Please let us know if it still occurs. If not we will be closing this.

**Comment by yahu1031** [comment] 2021-09-14 12:06
@sarika01 Please reopen if the issue still persists. Closing as of now

**Comment by sarika01** [comment] 2021-09-17 07:45
Tested with the current code on trunk branch today. This issue still exists. There is no error message shown as in the video above and no errors in the app log.
Steps to reproduce:
1. Reset an existing atsign or purchase a new one. Activate it.
2. Run the example app in at_onboarding_flutter package.
3. This screen is shown
![Simulator Screen Shot - iPhone 8 - 2021-09-17 at 13 14 34](https://user-images.githubusercontent.com/12222326/133744725-91d63852-cebb-465c-baf3-af0c8746d39e.png)

4. Even after waiting for 10mins, I did not get the email with OTP.

**Comment by yahu1031** [comment] 2021-09-17 10:08
Even I have tried it and it is reproducible. And when I try **resend the code**, It says the atsign is invalid. 

<!-- As we have observed that [Old staging server](https://my.staging.atsign.wtf) wasn't working, and all the latest changes take place in [New staging server](https://my.atsign.wtf), We are closing this issue. Reopen it if it continues the same with [new staging server](https://my.atsign.wtf) --!>

**Comment by yahu1031** [comment] 2021-09-17 10:34
As we have observed that [Staging server](https://my.staging.atsign.wtf) wasn't being used by any of the apps, and all the latest changes take place in [Dev server](https://my.atsign.wtf), We are closing this issue. Reopen it if it continues the same with [Dev server](https://my.atsign.wtf)

**Closed as completed** 2021-09-17 13:00 UTC
Labels: bug, 3 SP, PR19, PR20
